#:kivy 1.9.0
#: import SlideTransition kivy.uix.screenmanager.SlideTransition


ScreenManagement:

	GameView:



<GameView>
    canvas.before:
        BorderImage:
            texture: self.background_image.texture
            size: self.size
	Button:
		text: "click to flip"
		pos_hint: {"top":1, "left": 1}
		size_hint: (0.2, 0.2)
		on_press:
			root.sprite.flip_h()

	Button:
		text: "click to jump"
		pos_hint: {"top":1, "right": 1}
		size_hint: (0.2, 0.2)
		on_press:
			root.jump()
